### ISSUE TITLE
Email verification not sent

### ISSUE THREAD

**Issue by wcjord** [pangeachat/client-v0#23]
Expected behavior: When I set up an email for password recovery, the system sends an email to verify the email address.

Actual behavior: The email is not delivered.

To reproduce:
Go to security and password recovery, set up an email. Check your email inbox. It's not there!

**Comment by ptman** [comment]
SMTP from AWS seems to be blocked.

https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-email.md

**Comment by swati-singh-oodles** [comment]
Email verification is not working at the time of sign-up as well.

**Comment by ptman** [comment]
What are the address, port, username, password etc. we need to use to send email through SES?

**Comment by wcjord** [comment]
I think this is on @khanhhongpham now

**Comment by ptman** [comment]
Please test
