### ISSUE TITLE
Email not found error is occuring with valid email id 

### ISSUE THREAD

**Issue by swati-singh-oodles** [pangeachat/client-v0#24]
Steps to reproduce-:
1. Login to application “https://staging.pangea.chat/”.
2. Click on start button > Password Forgotten.
3.  User enter  valid email id which is linked at the time of sign-up.

Expected Result-: An email for OTP should sent at verified email id.
Actual Result -: “Email id not found” error is occuring

Screenshot-: 
![image](https://user-images.githubusercontent.com/111108425/184324624-4c2ca0cc-adf1-4c3f-9cff-4c025cfd6f25.png)

@akshaysharma1801 / @khanhhongpham

**Comment by paigempoole** [comment]
I also found this bug! I have registered the email paige.m.poole@gmail.com as my recovery email, but when I tried to use it to reset my password, I get this same error.
